"""Stable error codes + command states for the conversational dispatcher (Phase 4B.1).

Error codes are part of the API contract — callers (voice, tray, tests) branch on
them, so they never change spelling. Command states describe where a command is
in its lifecycle for the runtime/tray display.
"""

from __future__ import annotations

# --- error codes -------------------------------------------------------------------
FEATURE_DISABLED = "FEATURE_DISABLED"
INVALID_PLAN = "INVALID_PLAN"
UNSUPPORTED_INTENT = "UNSUPPORTED_INTENT"
TARGET_UNAVAILABLE = "TARGET_UNAVAILABLE"
TARGET_CHANGED = "TARGET_CHANGED"
ACTION_EXPIRED = "ACTION_EXPIRED"
CONFIRMATION_REQUIRED = "CONFIRMATION_REQUIRED"
CONFIRMATION_MISMATCH = "CONFIRMATION_MISMATCH"
AMBIGUOUS_TARGET = "AMBIGUOUS_TARGET"
SENSITIVE_FIELD_BLOCKED = "SENSITIVE_FIELD_BLOCKED"
BROWSER_UNAVAILABLE = "BROWSER_UNAVAILABLE"
EXECUTION_FAILED = "EXECUTION_FAILED"

# Phase 4C (WhatsApp) + 4D (email) integration codes.
LOGIN_REQUIRED = "LOGIN_REQUIRED"
CONTACT_NOT_FOUND = "CONTACT_NOT_FOUND"
CONTACT_AMBIGUOUS = "CONTACT_AMBIGUOUS"
CHAT_CHANGED = "CHAT_CHANGED"
DRAFT_CHANGED = "DRAFT_CHANGED"
SEND_BLOCKED = "SEND_BLOCKED"
# Phase 4D (email).
PROVIDER_UNSUPPORTED = "PROVIDER_UNSUPPORTED"
THREAD_NOT_FOUND = "THREAD_NOT_FOUND"
RECIPIENT_AMBIGUOUS = "RECIPIENT_AMBIGUOUS"
RECIPIENT_CHANGED = "RECIPIENT_CHANGED"
THREAD_CHANGED = "THREAD_CHANGED"
ATTACHMENT_BLOCKED = "ATTACHMENT_BLOCKED"
PROMPT_INJECTION_DETECTED = "PROMPT_INJECTION_DETECTED"

# Phase 5A (personal memory). Writes/updates/forgets are explicit-consent only.
MEMORY_DISABLED = "MEMORY_DISABLED"
MEMORY_NOT_FOUND = "MEMORY_NOT_FOUND"
DUPLICATE_MEMORY = "DUPLICATE_MEMORY"
MEMORY_CONFLICT = "MEMORY_CONFLICT"
SENSITIVE_CONTENT_BLOCKED = "SENSITIVE_CONTENT_BLOCKED"
CONSENT_REQUIRED = "CONSENT_REQUIRED"
NOTHING_TO_FORGET = "NOTHING_TO_FORGET"

# Phase 5B (multi-step tasks). Plans are validated deterministically before any
# execution; every effect still pauses for its own domain confirmation.
TASKS_DISABLED = "TASKS_DISABLED"
TASK_NOT_FOUND = "TASK_NOT_FOUND"
PLAN_TOO_LARGE = "PLAN_TOO_LARGE"
PLAN_HAS_CYCLE = "PLAN_HAS_CYCLE"
UNSUPPORTED_STEP = "UNSUPPORTED_STEP"
INVALID_STEP_ARGS = "INVALID_STEP_ARGS"
INVALID_DEPENDENCY = "INVALID_DEPENDENCY"
EMPTY_PLAN = "EMPTY_PLAN"
PLAN_NOT_APPROVED = "PLAN_NOT_APPROVED"
APPROVAL_MISMATCH = "APPROVAL_MISMATCH"
TASK_BUSY = "TASK_BUSY"
TASK_TIMEOUT = "TASK_TIMEOUT"
STEP_FAILED = "STEP_FAILED"
TASK_CANCELLED = "TASK_CANCELLED"
TASK_ALREADY_COMPLETED = "TASK_ALREADY_COMPLETED"
INVALID_TASK_STATE = "INVALID_TASK_STATE"

# Phase 5C (schedules + reminders). Creating/modifying a schedule is sensitive;
# dates are resolved deterministically and ambiguous ones are refused.
SCHEDULES_DISABLED = "SCHEDULES_DISABLED"
SCHEDULE_NOT_FOUND = "SCHEDULE_NOT_FOUND"
AMBIGUOUS_DATE = "AMBIGUOUS_DATE"
INVALID_DATE = "INVALID_DATE"
INVALID_RECURRENCE = "INVALID_RECURRENCE"
INVALID_TIMEZONE = "INVALID_TIMEZONE"
INVALID_SCHEDULE_STATE = "INVALID_SCHEDULE_STATE"
MAX_RUNS_REACHED = "MAX_RUNS_REACHED"
EMPTY_SCHEDULE = "EMPTY_SCHEDULE"

# Phase 5D (Activity Center). Read-only observability + safe control routing.
ACTIVITY_DISABLED = "ACTIVITY_DISABLED"
EVENT_NOT_FOUND = "EVENT_NOT_FOUND"
NOTHING_PENDING = "NOTHING_PENDING"
UNSUPPORTED_SERVICE = "UNSUPPORTED_SERVICE"
EXPORT_DISABLED = "EXPORT_DISABLED"

# Phase 6B (Security profiles + permissions). Central default-deny authorization.
PERMISSION_DENIED = "PERMISSION_DENIED"
PROFILE_INSUFFICIENT = "PROFILE_INSUFFICIENT"
ELEVATION_REQUIRED = "ELEVATION_REQUIRED"
LOCKED = "LOCKED"
UNLOCK_REQUIRED = "UNLOCK_REQUIRED"
UNLOCK_FAILED = "UNLOCK_FAILED"
ACCOUNT_LOCKED_OUT = "ACCOUNT_LOCKED_OUT"
INVALID_PROFILE = "INVALID_PROFILE"
GUEST_ISOLATION = "GUEST_ISOLATION"
ELEVATION_EXPIRED = "ELEVATION_EXPIRED"
NO_VERIFIER = "NO_VERIFIER"

# Phase 6A (Knowledge Vault). Documents are untrusted data; deletion is confirmed.
KNOWLEDGE_DISABLED = "KNOWLEDGE_DISABLED"
DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND"
UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"
FILE_TOO_LARGE = "FILE_TOO_LARGE"
TOO_MANY_PAGES = "TOO_MANY_PAGES"
DUPLICATE_DOCUMENT = "DUPLICATE_DOCUMENT"
ENCRYPTED_FILE = "ENCRYPTED_FILE"
EXTRACTION_FAILED = "EXTRACTION_FAILED"
EMPTY_DOCUMENT = "EMPTY_DOCUMENT"
INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
DOCUMENT_NOT_READY = "DOCUMENT_NOT_READY"

# Phase 6C (native desktop bridge). The desktop is a thin localhost client that
# authenticates with a short-lived UI session token; non-loopback callers are refused.
DESKTOP_DISABLED = "DESKTOP_DISABLED"
UI_TOKEN_REQUIRED = "UI_TOKEN_REQUIRED"
UI_TOKEN_INVALID = "UI_TOKEN_INVALID"
UI_TOKEN_EXPIRED = "UI_TOKEN_EXPIRED"
NON_LOCAL_BLOCKED = "NON_LOCAL_BLOCKED"

ERROR_CODES = frozenset({
    FEATURE_DISABLED, INVALID_PLAN, UNSUPPORTED_INTENT, TARGET_UNAVAILABLE,
    TARGET_CHANGED, ACTION_EXPIRED, CONFIRMATION_REQUIRED, CONFIRMATION_MISMATCH,
    AMBIGUOUS_TARGET, SENSITIVE_FIELD_BLOCKED, BROWSER_UNAVAILABLE, EXECUTION_FAILED,
    LOGIN_REQUIRED, CONTACT_NOT_FOUND, CONTACT_AMBIGUOUS, CHAT_CHANGED,
    DRAFT_CHANGED, SEND_BLOCKED, PROVIDER_UNSUPPORTED, THREAD_NOT_FOUND,
    RECIPIENT_AMBIGUOUS, RECIPIENT_CHANGED, THREAD_CHANGED, ATTACHMENT_BLOCKED,
    PROMPT_INJECTION_DETECTED,
    MEMORY_DISABLED, MEMORY_NOT_FOUND, DUPLICATE_MEMORY, MEMORY_CONFLICT,
    SENSITIVE_CONTENT_BLOCKED, CONSENT_REQUIRED, NOTHING_TO_FORGET,
    TASKS_DISABLED, TASK_NOT_FOUND, PLAN_TOO_LARGE, PLAN_HAS_CYCLE, UNSUPPORTED_STEP,
    INVALID_STEP_ARGS, INVALID_DEPENDENCY, EMPTY_PLAN, PLAN_NOT_APPROVED,
    APPROVAL_MISMATCH, TASK_BUSY, TASK_TIMEOUT, STEP_FAILED, TASK_CANCELLED,
    TASK_ALREADY_COMPLETED, INVALID_TASK_STATE,
    SCHEDULES_DISABLED, SCHEDULE_NOT_FOUND, AMBIGUOUS_DATE, INVALID_DATE,
    INVALID_RECURRENCE, INVALID_TIMEZONE, INVALID_SCHEDULE_STATE, MAX_RUNS_REACHED,
    EMPTY_SCHEDULE,
    ACTIVITY_DISABLED, EVENT_NOT_FOUND, NOTHING_PENDING, UNSUPPORTED_SERVICE,
    EXPORT_DISABLED,
    KNOWLEDGE_DISABLED, DOCUMENT_NOT_FOUND, UNSUPPORTED_FORMAT, FILE_TOO_LARGE,
    TOO_MANY_PAGES, DUPLICATE_DOCUMENT, ENCRYPTED_FILE, EXTRACTION_FAILED,
    EMPTY_DOCUMENT, INSUFFICIENT_EVIDENCE, DOCUMENT_NOT_READY,
    PERMISSION_DENIED, PROFILE_INSUFFICIENT, ELEVATION_REQUIRED, LOCKED,
    UNLOCK_REQUIRED, UNLOCK_FAILED, ACCOUNT_LOCKED_OUT, INVALID_PROFILE,
    GUEST_ISOLATION, ELEVATION_EXPIRED, NO_VERIFIER,
    DESKTOP_DISABLED, UI_TOKEN_REQUIRED, UI_TOKEN_INVALID, UI_TOKEN_EXPIRED,
    NON_LOCAL_BLOCKED,
})

# --- command states ----------------------------------------------------------------
LISTENING = "listening"
PLANNING = "planning"
AWAITING_CONFIRMATION = "awaiting_confirmation"
EXECUTING = "executing"
COMPLETED = "completed"
BLOCKED = "blocked"
FAILED = "failed"

COMMAND_STATES = frozenset({
    LISTENING, PLANNING, AWAITING_CONFIRMATION, EXECUTING, COMPLETED, BLOCKED, FAILED,
})
